BINDIR = /usr/sbin
PROG = reflector
CFLAGS = -g -Wall -Wextra -fno-strict-aliasing

SRCS = \
	bpf.c \
	checksum.c \
	hash.c \
	localaddrs.c \
	segments.c \
	sessions.c \
	reflector.c \

.include <prog.mk>
